<?php
    $status_colors = [
        30 => ['text-warning', 'Waiting for payment'],
        40 => ['text-info', 'Payment received'],
        60 => ['text-primary', 'On the way to customer'],
        70 => ['text-secondary', 'Received by customer'],
        80 => ['text-secondary', 'On the way back to merchant'],
        90 => ['text-secondary', 'Returned back to merchant']
    ];
?>
<nav class="navbar navbar-expand-lg navbar-light bg-white navbar-shadow">
    <div class="navbar-multiline mr-auto">
        <span class="navbar-brand" href="#0">Purchases</span>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?= $this->router->to('adminHome') ?>">Home</a></li>
                <li class="breadcrumb-item"><a href="<?= $this->router->to('adminProduct') ?>">Product</a></li>
                <li class="breadcrumb-item active" aria-current="page">Purchase</li>
            </ol>
        </nav>
    </div>
</nav>

<div class="container p-3">
    <div class="row">
        <div class="col-md-3">
            <div class="card mb-3">
                <form method="GET" class="card-body">
                    <h5 class="card-title">Search</h5>
                    <?= $form->field('q') ?>
                    <?= $form->field('status') ?>
                    <div class="text-right">
                        <button class="btn btn-primary">Find</button>
                    </div>
                </form>
            </div>
            <div class="card mb-3">
                <div class="card-body">
                    <div>Total item: <?= number_format($total); ?></div>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <?php if($purchases): ?>
                <?php $csrf = $form->csrfToken(); ?>
                <ul class="list-group list-group-flush card mb-3">
                    <?php foreach($purchases as $purchase): ?>
                        <li class="list-group-item">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">
                                    <?= $purchase->invoice->safe ?>
                                </h5>
                                <div>
                                    <div class="btn-group btn-group-sm" role="group" aria-label="Action">
                                        <a href="<?= $this->router->to('adminPurchaseDetails', ['id'=>$purchase->id]) ?>" class="btn btn-secondary" title="Details">
                                            <i class="fas fa-eye"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <small>
                                <span title="Created">
                                    <i class="far fa-calendar-plus"></i>
                                    <?= $purchase->created->format('M d, Y H:i') ?>
                                </span>
                                &middot;
                                <span title="Creator">
                                    <i class="fas fa-user"></i>
                                    <?= $purchase->user->fullname->safe ?>
                                </span>

                                <?php if(isset($status_colors[$purchase->status->value])): ?>
                                    <?php $status_color = $status_colors[$purchase->status->value]; ?>
                                    &middot;
                                    <span title="Status" class="<?= $status_color[0] ?>">
                                        <?= $status_color[1] ?>
                                    </span>
                                <?php endif; ?>
                            </small>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>

            <?php if($pages): ?>
                <?= $this->partial('shared/pagination', ['pages'=>$pages, 'align'=>'right']); ?>
            <?php endif; ?>
        </div>
    </div>
</div>
